-- MySQL Script generated by MySQL Workbench
-- Fri Jun  2 15:35:29 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ws-music-catalog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ws-music-catalog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ws-music-catalog` DEFAULT CHARACTER SET utf8 ;
USE `ws-music-catalog` ;

-- -----------------------------------------------------
-- Table `ws-music-catalog`.`artist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ws-music-catalog`.`artist` (
  `artist_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  `date_founded` DATE NOT NULL,
  `image_url` VARCHAR(200) NOT NULL,
  `genres` VARCHAR(45) NOT NULL,
  `popularity` INT NOT NULL,
  `follower` INT NOT NULL,
  `uri` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`artist_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ws-music-catalog`.`album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ws-music-catalog`.`album` (
  `album_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `date` DATE NOT NULL,
  `artist_id` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `total_tracks` INT NOT NULL,
  `image_url` VARCHAR(200) NOT NULL,
  `popularity` VARCHAR(45) NOT NULL,
  `uri` VARCHAR(45) NOT NULL,
  `url_tracks` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`album_id`),
  INDEX `fk_album_artist1_idx` (`artist_id` ASC) VISIBLE,
  CONSTRAINT `fk_album_artist1`
    FOREIGN KEY (`artist_id`)
    REFERENCES `ws-music-catalog`.`artist` (`artist_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ws-music-catalog`.`track`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ws-music-catalog`.`track` (
  `track_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `album_id` INT NOT NULL,
  `artist_id` INT NOT NULL,
  `release_date` DATE NOT NULL,
  `uri` VARCHAR(45) NOT NULL,
  `genres` VARCHAR(45) NOT NULL,
  `duration` INT NOT NULL,
  `track_number` INT NOT NULL,
  `popularity` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`track_id`),
  INDEX `fk_track_album1_idx` (`album_id` ASC, `artist_id` ASC) VISIBLE,
  CONSTRAINT `fk_track_album1`
    FOREIGN KEY (`album_id`)
    REFERENCES `ws-music-catalog`.`album` (`album_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
